spring:
  application:
    name: com.iago.flowlog
  datasource:
    url: jdbc:h2:mem:flowlogdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: never
  h2:
    console:
      enabled: true
